# Generated by Django 5.1.2 on 2024-10-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresource',
            name='resource_status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Xuất bản')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='resource_type',
            field=models.CharField(choices=[('document', 'Tài liệu'), ('video', 'Video'), ('slide', 'Bài giảng'), ('audio', 'Audio')], default='document', max_length=50),
        ),
    ]
